### PR TITLE
Output polyN stretches in `.cf_seq` file

### PR DESCRIPTION
**Pull request by theJasonFan**
Changed reduced GFA format to output where polyN stretches occur w.r.t output unitig tiling.

PolyN stretches are encoded `N\d`, with `N` prepended to the number of Ns.

Output tilings look like:
```
$ cat tiny.fa        
>I dna:chromosome chromosome:R64-1-1:I:1:230218:1 REF
NNNCACACACCACNCGTATTGAGG
$ cat tiny.cf_seq
Reference:1_Sequence:I	N3 3+ N1 2-
```

@rob-p @jamshed this might be a breaking change for consumers downstream.

### CODE REVIEW

**Comment by rickbeeloo** [comment]
Currently walks from the `cf_seq` are equivalent to those in the GFA format, hence "reduced GFA" I suppose, implementing this change would break that. This would be nice for looking at homopolymers specifically, but our application for example would require substantially more processing when having to check for the presence of homopolymer notations rather than 1:1 reading node ids. This seems to be a specific case rather than a general case so if pushed please make this optional @jamshed

**Comment by rob-p** [comment]
Hi @rickbeeloo,

  This change should apply only to the "reduced GFA" format. However, if you're using this currently and expect that this would be a breaking change, I think it would be possible to either (a) provide the modified output only when an additional flag is provided or (b) add an addition output "format" which is basically "reduced GFA with polyN tracking".  @jamshed — any preference among (a) or (b)?

--Rob

**Comment by jamshed** [comment]
Hi @rob-p and @rickbeeloo: interesting discussion! Outputting the poly-N stretches in the tilings this way would not satisfy the GFA-specs (which the "reduced" format encodes space-efficiently); see these paragraphs: [Path line](https://github.com/GFA-spec/GFA-spec/blob/master/GFA1.md#p-path-line) (for GFA 1) and [Group](https://github.com/GFA-spec/GFA-spec/blob/master/GFA2.md#group) (for GFA 2). I think that instead of introducing yet another output format, we can introduce something like a `--poly-N-stretch` flag, that would output these stretches (and would thus deviate from the GFA-specs). What do you think?

Regards.

**Comment by rickbeeloo** [comment]
I also think that would be the nicest! The tool we are working on will just use the "paths" so using the Cuttlefish reduced format is a big advantage - storage-wise. Currently, we can allow both the traditional GFA and reduced GFA as the path lines are equivalent.

**Comment by rob-p** [comment]
Going to merge this and then add the flag.

**Comment by rob-p** [comment]
Ok, I added the flag in 09f09bd84b64a45b5b379ed5696c8745cb801ced and checked that it works with @theJasonFan's tiny test case (we get the poly-N tiles with `--poly-N-stretch` and we don't get them without it).

Some command line parameter checking could be improved here by e.g. validating that this flag is only passed when GFA-reduced output format is requested.

**Pull request merged**
